version: "3.4"
services:
    redis:
        container_name: redis
        image: redis

        command: redis-server --requirepass C0KHfa7sa9AmzNpWzcAu9eC67Reip7R5M

        ports:
            - 6379:6379
        networks:
            - backend

    socket-server:
        container_name: master-socket-server
        build: .
        depends_on: [ redis ]
        ports:
            - 42069:42069
        volumes:
            - ./data:/src/app/data
            - ./log:/src/app/log
        networks:
            - backend

networks:
    backend:
        driver: bridge
